### ISSUE TITLE
Importing large JSON files is slow

### ISSUE THREAD

**Issue by tehandyb** [rollup/rollup-plugin-json#40]
Hi I was trying to import a large topo json file (718 kb), and rollup is not able to finish building. The topo json file is for the world map and has many nested values which is why I'm guessing it goes slow. Is this due to tree shaking? Is there a way to just import the json file as it is, and do no processing on it so it can be imported faster?

**Comment by njbotkin** [comment]
I believe the problem here is babel, not rollup.  I looked at your project from before you switched to webpack.  You were ignoring json files incorrectly; shoulda been `exclude: ['node_modules/**', '**/*.json']`

I ran into this too, and getting babel off of my 500kb json file resulted in 3x faster builds.

**Comment by tehandyb** [comment]
Wow can't believe I did that. You were right, thank you so much for investigating! Now I'm getting 3 second build times. 😆
