### ISSUE TITLE
Weird/gunky default JSON import output

### ISSUE THREAD

**Issue by maranomynet** [rollup/rollup-plugin-json#5]
Why does 

```js
import data from './data.json';
```

...result in this:

```js
var key = "value";
var key2 = 999;
var object = {"prop":999,"prop2":"value"};
var require$$0 = {
    key: key,
    key2: key2,
    object: object
};
var data = require$$0;
```

...instead of simply this:

```js
var require$$0 = {
  "key": "value",
  "key2": 999,
  "object": {
    "prop": 999,
    "prop2": "value"
  }
};
var data = require$$0;
```

**Comment by Victorystick** [comment]
Because then you can `import { key } from './data.json';` and only get what you use.

**Comment by maranomynet** [comment]
That explanation doesn't quite add up because when I do `import { key } from './data';` I get this super-neat little thing:

```js
var key = "value";
```

...and no extra gunk.

**Comment by Rich-Harris** [comment]
Exactly! rollup-plugin-json always generates the 'gunk' whatever – it's just that when you only use `key` in the bundle, all the other stuff can be removed. This is really handy for doing e.g.

```js
import { version } from '../package.json'; // you don't want the rest of this file

// ...
myLib.VERSION = version
export default myLib;
```

There's a very slightly increase in the number of bytes generated if you use the default export, but a good minifier will see to that.

**Comment by maranomynet** [comment]
OK, thanks for the explanation. 

Doing this only for properties that are actually imported directly by name, would of course be more elegant, but I understand that might not be worth the trouble.

**Comment by Rich-Harris** [comment]
It's not so much a question of whether it's worth the trouble, it's that it's basically impossible. If module transformers were aware of what was being imported from the module being transformed, then if you had something like this...

```js
// main.js
import { foo } from './x.js';
import './y.js';


// y.js
import { bar } from './y.js';
```

then the first `import` would cause the processing of `x.js` to happen (with knowledge of the `foo` import, in this hypothetical scenario). The second would cause `y.js` to be processed, but then we'd have to *reprocess* `x.js` because of the new `bar` import. And if the result was different it could cause all sorts of chaos.

Of course, if you could resolve the entire dependency graph ahead of time you wouldn't have that problem, but that's totally impossible because modules need to be transformed before you can parse them and extract the dependency graph in the first place...

Closing this issue :)
